name: CI - Build et Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  tests-backend:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./backend

    steps:
      - name: Récupérer le code
        uses: actions/checkout@v4

      - name: Installer Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'

      - name: Lancer les tests Maven
        run: mvn test

  tests-frontend:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./frontend

    steps:
      - name: Récupérer le code
        uses: actions/checkout@v4

      - name: Installer Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Installer les dépendances
        run: npm ci

      - name: Lancer les tests Angular
        run: npm test -- --watch=false --browsers=ChromeHeadless

  build-docker:
    runs-on: ubuntu-latest
    needs: [tests-backend, tests-frontend]

    steps:
      - name: Récupérer le code
        uses: actions/checkout@v4

      - name: Construire l'image Docker du backend
        run: docker build -t innotechfusion-backend ./backend

      - name: Construire l'image Docker du frontend
        run: docker build -t innotechfusion-frontend ./frontend
